# Generated by Django 3.2.15 on 2022-08-31 08:20

import cms.core.db.fields
import cms.core.utils.editorjs
import cms.core.utils.json_serializer
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=cms.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=cms.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('content', cms.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=cms.core.utils.editorjs.clean_editor_js)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_url', models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_posts', 'Manage posts.'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('alt', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('IMAGE', 'An uploaded image or an URL to an image'), ('VIDEO', 'A URL to an external video')], default='IMAGE', max_length=32)),
                ('external_url', models.CharField(blank=True, max_length=256, null=True)),
                ('oembed_data', models.JSONField(blank=True, default=dict)),
                ('to_remove', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=35)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', cms.core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=cms.core.utils.editorjs.clean_editor_js)),
            ],
            options={
                'ordering': ('language_code', 'post', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=cms.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=cms.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_post_types_and_attributes', 'Manage post types and attributes.'),),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='posttype',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='posttype_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='posttype',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='posttype_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='posttype',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'slug'], name='post_postty_name_e8ac46_gin'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='post.post'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='post.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.posttype'),
        ),
        migrations.AlterUniqueTogether(
            name='posttranslation',
            unique_together={('language_code', 'post')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='post_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='post_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'slug'], name='post_post_title_b1e481_gin'),
        ),
    ]
