# Generated by Django 2.0.3 on 2018-07-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("post", "0002_auto_20180321_0417")]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("slug",),
                "permissions": (("manage_posts", "Manage posts."),),
            },
        )
    ]
