# Generated by Django 2.0.3 on 2018-08-03 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post", "0003_auto_20180719_0520")]

    operations = [
        migrations.CreateModel(
            name="PostTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(70)],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="post.Post",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="posttranslation", unique_together={("language_code", "post")}
        ),
    ]
