# Generated by Django 2.2.10 on 2020-02-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_auto_20200129_0717"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posttranslation",
            options={"ordering": ("language_code", "post")},
        ),
    ]
