# Generated by Django 3.1 on 2021-01-07 12:07

from django.db import migrations
from django.db.models import F

import cms.core.db.fields
import cms.core.utils.editorjs


def clean_content_field(apps, schema_editor):
    Post = apps.get_model("post", "Post")
    PostTranslation = apps.get_model("post", "PostTranslation")

    Post.objects.all().update(content="{}")
    PostTranslation.objects.all().update(content="{}")


def migrate_content_json_into_content_field(apps, schema_editor):
    Post = apps.get_model("post", "Post")
    PostTranslation = apps.get_model("post", "PostTranslation")

    Post.objects.all().update(content=F("content_json"))
    PostTranslation.objects.all().update(content=F("content_json"))


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0017_posttype"),
    ]

    operations = [
        migrations.RunPython(
            clean_content_field,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=cms.core.db.fields.SanitizedJSONField(
                blank=True,
                default=dict,
                sanitizer=cms.core.utils.editorjs.clean_editor_js,
            ),
        ),
        migrations.AlterField(
            model_name="posttranslation",
            name="content",
            field=cms.core.db.fields.SanitizedJSONField(
                blank=True,
                default=dict,
                sanitizer=cms.core.utils.editorjs.clean_editor_js,
            ),
        ),
        migrations.RunPython(
            migrate_content_json_into_content_field,
            migrations.RunPython.noop,
        ),
    ]
