# Generated by Django 3.1.7 on 2021-03-08 11:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0020_update_content_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="post_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="post_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posttype",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["private_metadata"], name="posttype_p_meta_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posttype",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metadata"], name="posttype_meta_idx"
            ),
        ),
    ]
