# Generated by Django 3.2.2 on 2021-05-26 08:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0022_alter_posttranslation_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title", "slug"], name="post_post_title_964714_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="posttype",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "slug"], name="post_postty_name_7c1cb8_gin"
            ),
        ),
    ]
