# Generated by Django 3.2.15 on 2022-08-29 09:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_alter_post_publication_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_post_title_964714_gin',
        ),
        migrations.RemoveIndex(
            model_name='posttype',
            name='post_postty_name_7c1cb8_gin',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'slug'], name='post_post_title_b1e481_gin'),
        ),
        migrations.AddIndex(
            model_name='posttype',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'slug'], name='post_postty_name_e8ac46_gin'),
        ),
    ]
