# Generated by Django 2.0.3 on 2018-03-21 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="seo_description",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(300)],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_title",
            field=models.CharField(
                blank=True,
                max_length=70,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(70)],
            ),
        ),
    ]
