# Generated by Django 2.2.3 on 2019-07-15 07:51
from django.db import migrations
from draftjs_sanitizer import clean_draft_js
from html_to_draftjs import html_to_draftjs

from ...core.db.fields import SanitizedJSONField
from ...core.utils.draftjs import json_content_to_raw_text


def convert_posts_html_to_json(apps, schema_editor):
    Post = apps.get_model("post", "Post")
    qs = Post.objects.all()

    for post in qs:
        content_json = post.content_json
        content_raw = json_content_to_raw_text(content_json)

        # Override the JSON content if there was nothing in it
        if not content_raw.strip():
            post.description_json = html_to_draftjs(post.content)
            post.save(update_fields=["content_json"])

    PostTranslation = apps.get_model("post", "PostTranslation")
    qs = PostTranslation.objects.all()

    for translation in qs:
        content_json = translation.content_json
        content_raw = json_content_to_raw_text(content_json)

        # Override the JSON content if there was nothing in it
        if not content_raw.strip():
            translation.description_json = html_to_draftjs(translation.content)
            translation.save(update_fields=["content_json"])


def sanitize_posts_json(apps, schema_editor):
    Post = apps.get_model("post", "Post")
    qs = Post.objects.all()

    for post in qs:
        post.content_json = clean_draft_js(post.content_json)
        post.save(update_fields=["content_json"])

    PostTranslation = apps.get_model("post", "PostTranslation")
    qs = PostTranslation.objects.all()

    for post in qs:
        post.content_json = clean_draft_js(post.content_json)
        post.save(update_fields=["content_json"])


class Migration(migrations.Migration):

    dependencies = [("post", "0007_auto_20190225_0252")]

    operations = [
        migrations.RunPython(convert_posts_html_to_json),
        migrations.RunPython(sanitize_posts_json),
        migrations.AlterField(
            model_name="post",
            name="content_json",
            field=SanitizedJSONField(
                blank=True, default=dict, sanitizer=clean_draft_js
            ),
        ),
        migrations.AlterField(
            model_name="posttranslation",
            name="content_json",
            field=SanitizedJSONField(
                blank=True, default=dict, sanitizer=clean_draft_js
            ),
        ),
    ]
