# Generated by Django 3.0.6 on 2020-07-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_auto_20200217_0350"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posttranslation",
            options={"ordering": ("language_code", "post", "pk")},
        ),
    ]
