# Generated by Django 3.1.5 on 2021-01-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0018_migrate_content_json_into_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content_json",
        ),
        migrations.RemoveField(
            model_name="posttranslation",
            name="content_json",
        ),
    ]
