# Generated by Django 3.1.5 on 2021-02-08 11:02

from django.db import migrations

import saleor.core.db.fields
import saleor.core.utils.editorjs


def update_empty_content_field(apps, schema_editor):
    Post = apps.get_model("post", "Post")
    PostTranslation = apps.get_model("post", "PostTranslation")

    Post.objects.filter(content={}).update(content=None)
    PostTranslation.objects.filter(content={}).update(content=None)


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0019_auto_20210125_0905"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True,
                null=True,
                sanitizer=saleor.core.utils.editorjs.clean_editor_js,
            ),
        ),
        migrations.AlterField(
            model_name="posttranslation",
            name="content",
            field=saleor.core.db.fields.SanitizedJSONField(
                blank=True,
                null=True,
                sanitizer=saleor.core.utils.editorjs.clean_editor_js,
            ),
        ),
        migrations.RunPython(
            update_empty_content_field,
            migrations.RunPython.noop,
        ),
    ]
