# Generated by Django 3.2.15 on 2022-08-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20220829_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
